from .full_game_summary_state import FullGameSummaryStateDto
from .full_game_playing_state import FullGamePlayingStateDto
from .full_game_waiting_state import FullGameWaitingStateDto

FullGameStateDto = FullGamePlayingStateDto | FullGameWaitingStateDto | FullGameSummaryStateDto
